version: "3.9"

services:

  keycloak:
    image: 'jboss/keycloak:16.1.1'
    networks:
      - back
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/oidc-realm.json
      - PROXY_ADDRESS_FORWARDING=true
    expose:
      - "8080"
    ports:
      - "8090:8080"
    volumes:
      - './keycloak/oidc-realm.json:/tmp/oidc-realm.json'

networks:
  back:
    driver: bridge
